# SCRIPT (MAIN PROGRAM)
SCRIPT=winpager
MAN=$(SCRIPT).1
# COMMANDS
DELETE=rm -f
INSTALL_RX=install -Dm755
INSTALL_RO=install -Dm644
# LOCATIONS
PREFIX=/usr
BINDIR=$(DESTDIR)$(PREFIX)/bin
MANDIR=$(DESTDIR)$(PREFIX)/share/man/man1

install:
	$(INSTALL_RX) $(SCRIPT) $(BINDIR)/$(SCRIPT)
	$(INSTALL_RO) $(MAN) $(MANDIR)/$(MAN)

uninstall:
	$(DELETE) $(BINDIR)/$(SCRIPT)
	$(DELETE) $(MANDIR)/$(MAN)
