.\" winpager man page
.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.ie t .ds Tx \s-1T\v'.4n'\h'-.1667'E\v'-.4n'\h'-.125'X\s0
. el  .ds Tx TeX
.de Id
. ds Yr \\$4
. substring Yr 0 3
. ds Mn \\$4
. substring Mn 5 6
. ds Dy \\$4
. substring Dy 8 9
. \" ISO 8601 date, complete format, extended representation
. ds Dt \\*(Yr-\\*(Mn-\\*(Dy
..
.TH WINPAGER 1 "winpager (git)" "User Commands"
.hy 0
.
.SH NAME
winpager \- A dynamic window paging system for X\.Org \fIhttp://www\.x\.org/wiki\fR\.
.o
.
.SH "DESCRIPTION"
.B winpager
This tool allows windows to have numbers assigned to them, which can then be used to switch to the desktop containing the assigned window and focus on it\.
.
.P
To make best use of this script, keyboard shortcuts should be assigned to the \fBwinpager set\fR and \fBwinpager get\fR for a range of numbers, as well as possibly ones for \fBwinpager clear\fR and \fBwinpager toggle\fR\.
.
.SH "REQUIREMENTS"
.B wmctrl
\fIhttp://tomas\.styblo\.name/wmctrl\fR
.
.P
.B xprop
\fIhttp://www.x.org/wiki\fR
.
.P
.B xwininfo
\fIhttp://www\.x\.org/wiki\fR
.
.P
.B bash
\fIhttp://www\.gnu\.org/software/bash\fR
.
.SH "USAGE"
\fBwinpager [command] {num(s)}\fR
.
.SS "Commands"
.TP
.BR \-set " {num}, " set " {num}"
assign a window to a pager {num}
.TP
.P
.TP
.BR \-get " {num}, " get " {num}"
go to its desktop and focus {num}
.TP
.P
.TP
.BR \-toggle ", " toggle
toggle focus between windows 1 and 2
.TP
.P
.TP
.BR \-toggle " {num} {num}, " toggle " {num} {num}"
toggle focus between windows {num} and {num}
.TP
.P
.TP
.BR \-unset " {num}, " unset " {num}"
unassign the window from pager {num}
.TP
.P
.TP
.BR \-clear ", " clear
remove all assigned windows from the pager
.TP
.P
.TP
.BR \-help ", " help
show the help
.
.SH "CREDITS"
Written by Kevin MacMartin:
.
.IP "\(bu" 4
GitHub Projects \fIhttps://github\.com/prurigro\fR
.
.IP "\(bu" 4
Arch Linux AUR Packages \fIhttps://aur\.archlinux\.org/packages/?SeB=m&K=prurigro\fR
.
.SH "LICENSE"
Licensed under the MIT license \fIhttp://opensource\.org/licenses/MIT\fR\.
